spring:
  datasource:
    url: jdbc:postgresql://localhost:5500/SpringBoot
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update